export type WorldCurrency = { code: string; name: string; symbol: string };

export const WORLD_CURRENCIES: WorldCurrency[] = [
  { code: "XOF", name: "Franc CFA BCEAO", symbol: "F CFA" },
  { code: "XAF", name: "Franc CFA BEAC", symbol: "F CFA" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "USD", name: "Dollar américain", symbol: "$" },
  { code: "GBP", name: "Livre sterling", symbol: "£" },
  { code: "JPY", name: "Yen japonais", symbol: "¥" },
  { code: "CNY", name: "Yuan chinois", symbol: "¥" },
  { code: "CHF", name: "Franc suisse", symbol: "CHF" },
  { code: "CAD", name: "Dollar canadien", symbol: "$" },
  { code: "AUD", name: "Dollar australien", symbol: "$" },
  { code: "MAD", name: "Dirham marocain", symbol: "MAD" },
  { code: "NGN", name: "Naira nigérian", symbol: "₦" },
  { code: "GHS", name: "Cedi ghanéen", symbol: "₵" },
  { code: "ZAR", name: "Rand sud-africain", symbol: "R" },
  { code: "KES", name: "Shilling kényan", symbol: "KSh" },
  { code: "EGP", name: "Livre égyptienne", symbol: "E£" },
  { code: "TND", name: "Dinar tunisien", symbol: "DT" },
  { code: "DZD", name: "Dinar algérien", symbol: "DA" },
  { code: "XPF", name: "Franc Pacifique", symbol: "F" },
  { code: "BRL", name: "Real brésilien", symbol: "R$" },
  { code: "MXN", name: "Peso mexicain", symbol: "$" },
  { code: "ARS", name: "Peso argentin", symbol: "$" },
  { code: "CLP", name: "Peso chilien", symbol: "$" },
  { code: "COP", name: "Peso colombien", symbol: "$" },
  { code: "PEN", name: "Sol péruvien", symbol: "S/" },
  { code: "VES", name: "Bolivar vénézuélien", symbol: "Bs" },
  { code: "UYU", name: "Peso uruguayen", symbol: "$" },
  { code: "PYG", name: "Guarani paraguayen", symbol: "₲" },
  { code: "BOB", name: "Boliviano", symbol: "Bs" },
  { code: "INR", name: "Roupie indienne", symbol: "₹" },
  { code: "PKR", name: "Roupie pakistanaise", symbol: "₨" },
  { code: "BDT", name: "Taka bangladais", symbol: "৳" },
  { code: "LKR", name: "Roupie sri-lankaise", symbol: "₨" },
  { code: "NPR", name: "Roupie népalaise", symbol: "₨" },
  { code: "VND", name: "Dong vietnamien", symbol: "₫" },
  { code: "THB", name: "Baht thaïlandais", symbol: "฿" },
  { code: "IDR", name: "Roupie indonésienne", symbol: "Rp" },
  { code: "MYR", name: "Ringgit malaisien", symbol: "RM" },
  { code: "PHP", name: "Peso philippin", symbol: "₱" },
  { code: "SGD", name: "Dollar de Singapour", symbol: "$" },
  { code: "HKD", name: "Dollar Hong Kong", symbol: "$" },
  { code: "TWD", name: "Dollar taïwanais", symbol: "NT$" },
  { code: "KRW", name: "Won sud-coréen", symbol: "₩" },
  { code: "AED", name: "Dirham EAU", symbol: "AED" },
  { code: "SAR", name: "Riyal saoudien", symbol: "﷼" },
  { code: "QAR", name: "Riyal qatari", symbol: "﷼" },
  { code: "KWD", name: "Dinar koweïtien", symbol: "KD" },
  { code: "BHD", name: "Dinar bahreïni", symbol: "BD" },
  { code: "OMR", name: "Rial omanais", symbol: "﷼" },
  { code: "JOD", name: "Dinar jordanien", symbol: "JD" },
  { code: "LBP", name: "Livre libanaise", symbol: "L£" },
  { code: "TRY", name: "Livre turque", symbol: "₺" },
  { code: "ILS", name: "Shekel israélien", symbol: "₪" },
  { code: "RUB", name: "Rouble russe", symbol: "₽" },
  { code: "UAH", name: "Hryvnia ukrainienne", symbol: "₴" },
  { code: "PLN", name: "Zloty polonais", symbol: "zł" },
  { code: "CZK", name: "Couronne tchèque", symbol: "Kč" },
  { code: "HUF", name: "Forint hongrois", symbol: "Ft" },
  { code: "RON", name: "Leu roumain", symbol: "lei" },
  { code: "BGN", name: "Lev bulgare", symbol: "лв" },
  { code: "RSD", name: "Dinar serbe", symbol: "дин" },
  { code: "HRK", name: "Kuna croate", symbol: "kn" },
  { code: "SEK", name: "Couronne suédoise", symbol: "kr" },
  { code: "NOK", name: "Couronne norvégienne", symbol: "kr" },
  { code: "DKK", name: "Couronne danoise", symbol: "kr" },
  { code: "ISK", name: "Couronne islandaise", symbol: "kr" },
  { code: "BYN", name: "Rouble biélorusse", symbol: "Br" },
  { code: "GEL", name: "Lari géorgien", symbol: "₾" },
  { code: "AMD", name: "Dram arménien", symbol: "֏" },
  { code: "AZN", name: "Manat azerbaïdjanais", symbol: "₼" },
  { code: "KZT", name: "Tenge kazakh", symbol: "₸" },
  { code: "UZS", name: "Sum ouzbek", symbol: "so'm" },
  { code: "KGS", name: "Som kirghize", symbol: "с" },
  { code: "TJS", name: "Somoni tadjik", symbol: "SM" },
  { code: "TMT", name: "Manat turkmène", symbol: "T" },
  { code: "MNT", name: "Tugrik mongol", symbol: "₮" },
  { code: "MMK", name: "Kyat birman", symbol: "K" },
  { code: "KHR", name: "Riel cambodgien", symbol: "៛" },
  { code: "LAK", name: "Kip laotien", symbol: "₭" },
  { code: "BND", name: "Dollar Brunei", symbol: "$" },
  { code: "FJD", name: "Dollar Fidji", symbol: "$" },
  { code: "NZD", name: "Dollar néo-zélandais", symbol: "$" },
  { code: "PGK", name: "Kina Papouasie", symbol: "K" },
  { code: "SBD", name: "Dollar Salomon", symbol: "$" },
  { code: "TOP", name: "Pa'anga Tonga", symbol: "T$" },
  { code: "VUV", name: "Vatu Vanuatu", symbol: "VT" },
  { code: "WST", name: "Tala Samoa", symbol: "T" },
  { code: "MOP", name: "Pataca Macao", symbol: "MOP$" },
  { code: "BWP", name: "Pula botswanais", symbol: "P" },
  { code: "MUR", name: "Roupie mauricienne", symbol: "₨" },
  { code: "SCR", name: "Roupie seychelloise", symbol: "₨" },
  { code: "MZN", name: "Metical mozambicain", symbol: "MT" },
  { code: "AOA", name: "Kwanza angolais", symbol: "Kz" },
  { code: "ZMW", name: "Kwacha zambien", symbol: "ZK" },
  { code: "MWK", name: "Kwacha malawite", symbol: "MK" },
  { code: "BIF", name: "Franc burundais", symbol: "FBu" },
  { code: "RWF", name: "Franc rwandais", symbol: "FRw" },
  { code: "CDF", name: "Franc congolais", symbol: "FC" },
  { code: "DJF", name: "Franc Djibouti", symbol: "Fdj" },
  { code: "KMF", name: "Franc comorien", symbol: "CF" },
  { code: "MGA", name: "Ariary malgache", symbol: "Ar" },
  { code: "ETB", name: "Birr éthiopien", symbol: "Br" },
  { code: "ERN", name: "Nakfa érythréen", symbol: "Nfk" },
  { code: "SOS", name: "Shilling somalien", symbol: "Sh" },
  { code: "SDG", name: "Livre soudanaise", symbol: "ج.س" },
  { code: "SSP", name: "Livre sud-soudanaise", symbol: "£" },
  { code: "UGX", name: "Shilling ougandais", symbol: "USh" },
  { code: "TZS", name: "Shilling tanzanien", symbol: "TSh" },
  { code: "ZWL", name: "Dollar zimbabwéen", symbol: "$" },
  { code: "NAD", name: "Dollar namibien", symbol: "$" },
  { code: "SZL", name: "Lilangeni swazi", symbol: "L" },
  { code: "LSL", name: "Loti lesothan", symbol: "L" },
  { code: "GMD", name: "Dalasi gambien", symbol: "D" },
  { code: "GNF", name: "Franc guinéen", symbol: "FG" },
  { code: "SLL", name: "Leone sierra-léonais", symbol: "Le" },
  { code: "LRD", name: "Dollar libérien", symbol: "$" },
  { code: "SLE", name: "Leone (nouveau)", symbol: "Le" },
  { code: "CVE", name: "Escudo cap-verdien", symbol: "$" },
  { code: "STN", name: "Dobra Santomé", symbol: "Db" },
  { code: "MRU", name: "Ouguiya mauritanienne", symbol: "UM" },
  { code: "LYD", name: "Dinar libyen", symbol: "LD" },
  { code: "YER", name: "Rial yéménite", symbol: "﷼" },
  { code: "IRR", name: "Rial iranien", symbol: "﷼" },
  { code: "AFN", name: "Afghani afghan", symbol: "؋" },
  { code: "IQD", name: "Dinar irakien", symbol: "ع.د" },
  { code: "SYP", name: "Livre syrienne", symbol: "£" },
  { code: "JMD", name: "Dollar jamaïcain", symbol: "$" },
  { code: "TTD", name: "Dollar Trinité", symbol: "$" },
  { code: "BBD", name: "Dollar barbadien", symbol: "$" },
  { code: "BZD", name: "Dollar bélizien", symbol: "$" },
  { code: "BSD", name: "Dollar bahaméen", symbol: "$" },
  { code: "KYD", name: "Dollar Caïmans", symbol: "$" },
  { code: "XCD", name: "Dollar Caraïbes", symbol: "$" },
  { code: "HTG", name: "Gourde haïtienne", symbol: "G" },
  { code: "DOP", name: "Peso dominicain", symbol: "$" },
  { code: "CUP", name: "Peso cubain", symbol: "$" },
  { code: "GTQ", name: "Quetzal guatémaltèque", symbol: "Q" },
  { code: "HNL", name: "Lempira hondurien", symbol: "L" },
  { code: "NIO", name: "Cordoba nicaraguayen", symbol: "C$" },
  { code: "CRC", name: "Colon costaricain", symbol: "₡" },
  { code: "PAB", name: "Balboa panaméen", symbol: "B/." },
  { code: "BWP", name: "Pula botswanais", symbol: "P" },
];

export const DEFAULT_CURRENCY = "XOF";

export function getCurrencyInfo(code: string): WorldCurrency | undefined {
  return WORLD_CURRENCIES.find((c) => c.code === code);
}
